### ISSUE TITLE
Error while calling the getSnaps();

### ISSUE THREAD

**Issue by joaovarelas** [JorgenPhi/php-snapchat#106]
Hello,

I've just cloned your repo and trying to run it but without success...

Notice: Undefined property: Snapchat::$cache in C:\xampp\htdocs\src\snapchat.php on line 234  Fatal error: Call to a member function get() on null in C:\xampp\htdocs\src\snapchat.php on line 234

Thanks

**Comment by mgp25** [comment]
@joaovarelas use https://github.com/mgp25/SC-API

this repo is outdated
