### ISSUE TITLE
A notice and fatal error when fetching feed

### ISSUE THREAD

**Issue by martynball** [JorgenPhi/php-snapchat#29]
I have successfully imported the snapchat.php file using require_once, seems to logged in successfully as it's returning an object. 

But when I try and fetch my feed i'm getting the following errors:
Notice: Undefined property: Snapchat::$cache in C:\xampp\htdocs\snapchat\src\snapchat.php on line 234

Fatal error: Call to a member function get() on a non-object in C:\xampp\htdocs\snapchat\src\snapchat.php on line 234

**Comment by pank123** [comment]
when i use with var_dump its still give me same error

Notice: Undefined property: Snapchat::$cache in D:\Xampp\htdocs\phpsnapchat\src\snapchat.php on line 317

Fatal error: Call to a member function get() on a non-object in D:\Xampp\htdocs\phpsnapchat\src\snapchat.php on line 317

**Comment by mgp25** [comment]
@pank123 this code is outdated. Use this one instead: https://github.com/mgp25/SC-API

**Comment by pank123** [comment]
Hello thanks for give me this url
I have integrate it and first time it was work for me but now its give me 
Error: UNAUTHORIZED
Notice: Trying to get property of non-object in D:\Xampp\htdocs\snapchtapi\src\snapchat.php on line 3079

**Comment by mgp25** [comment]
@pank123 you have to create a casper account, please read the wiki here: https://github.com/mgp25/SC-API

**Comment by pank123** [comment]
I have create the caster account and set the api key and secret key but still its give me unauthorised error it work for me 2 times but now suddently its stop and give me this error.

**Comment by pank123** [comment]
I have create the caster account and set the api key and secret key but still its give me unauthorised error it work for me 2 times but now suddently its stop and give me this error.

**Comment by mgp25** [comment]
@pank123 create an issue there:  https://github.com/mgp25/SC-API

Not here, and post there the debug log
