### ISSUE TITLE
Research:

### ISSUE THREAD

**Issue by JorgenPhi** [JorgenPhi/php-snapchat#30]
Hey everybody! I was making great progress analyzing the new API, but my IP address was recently blocked so I figured now would be a good time to fill you all in. 

(This was taken from version 5.0.2 on android && is likely missing endpoints. Snapchat refused my SSL certificate for about 25% of the connections.)

/loq is the new major endpoint. It contains:
/login  - (nearly identical to /bq/login)
/all_updates
/conversation 
/conversations 
/conversation_post_messages
/send - (nearly identical to /ph/send)

/bq contains these new endpoints:
/chat_typing
/upload_chat_media

Now, the "chat media" has a different encryption algorithm than snaps, and I have not found a way to decrypt them. Any help on this would be useful. 

Use this issue to document any findings in the new API so we can build an updated library. :)

Thanks.

**Comment by KyleBoyer** [comment]
Just removed my lg.php dependency(it's just used to analytical log data), and the generateMediaID works for me, but something else is causing the upload function to fail. If you want to test it on my server, email me at kyleboyerplus <at> gmail <dot> com
