### ISSUE TITLE
Can't get snap to send!

### ISSUE THREAD

**Issue by Dgameman1** [JorgenPhi/php-snapchat#63]
<?php

    require_once('src/snapchat.php');

    // Log in:
    $snapchat = new Snapchat('XXX', 'XXX');

    // Upload a snap and send it to me for 8 seconds:
    $id = $snapchat->upload(
    Snapchat::MEDIA_IMAGE,
    file_get_contents('/images/arielol.jpg')
    );
    $snapchat->send($id, array('allenbgd'), 4);

    // Log out:
    $snapchat->logout();

    ?>

For whatever reason, nothing is being sent. And when I tried using the test I get an error saying
"Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /snap/tests/phpSnapchatTest.php on line 3"

**Comment by Dgameman1** [comment]
So what do you suggest I do? Just wait till it gets fixed?
@cuonic

**Comment by cuonic** [comment]
You could try participating in the development of a solution, I've gave 
you the request and response parameters of the new upload system, you 
just need to change a few things in the PHP class.

**Comment by KyleBoyer** [comment]
> You could try participating in the development of a solution, I've gave
> you the request and response parameters of the new upload system, you
> just need to change a few things in the PHP class.

I just adjusted my code and tried those parameters with that endpoint, and I still get back a 401 Unauthorized response.

**Comment by cuonic** [comment]
Got it working with a few modifications, here is my testing code : http://files.lab.cuonic.com/NWI2MzJ

**Comment by Dgameman1** [comment]
@cuonic  Page not found :O

**Comment by cuonic** [comment]
@Dgameman1 Page not found for the download, when uploading a snap, when sending the snap ?

**Comment by Dgameman1** [comment]
@cuonic http://files.lab.cuonic.com/NWI2MzJ says 404 Not Found

**Comment by cuonic** [comment]
@Dgameman1 Sorry about that, seems to work for other people though. Try this : http://dev.cuonic.com/SnapUpload.zip

**Comment by Dgameman1** [comment]
Hmm that's really strange. Still 404
http://i.imgur.com/jkBRQAn.png
Let me try going through proxy

**Comment by Dgameman1** [comment]
And it worked ... @cuonic Very weird.
Thank you though! Let me try this out!

**Comment by cuonic** [comment]
@Dgameman1 Check your DNS servers they don't see very... up to date :) In upload.php you just need to add your Snapchat username and password for it to work.

**Comment by Dgameman1** [comment]
@cuonic  http://i.imgur.com/txR6m7H.png :( I promise I'm not retarded

**Comment by cuonic** [comment]
I've got exactly the same code and it's working good. If you're getting "Error encountered" then it's good news, it means that the upload was successful, so it's just the "sending" of the snap that screws up. 

Use the following code to debug the sending : 

````
<?php

if($_POST) {
    require_once("snapchat.php");

    $snapchat = new Snapchat();
    
    $login = $snapchat->login('USERNAME', 'PASSWORD');

    if(filesize($_FILES['image']['tmp_name']) > 1000000) {
        $message = "File too big.";
    } else {
        $upload = $snapchat->upload(Snapchat::MEDIA_IMAGE, file_get_contents($_FILES['image']['tmp_name']));

        if($upload['error'] == 1) {
        	$message = $upload['message'];	
        } else {
		    $return = $snapchat->send($upload['media_id'], array($_POST['username']), $_POST['seconds']);

			echo "<pre>";
			var_dump($return);
			echo "</pre>";

		    if($return['error'] == 0) {
		        $message = "Snap sent.";
		    } else {
		        $message = "Error encountered.";
		    }
		}
    }
}

?>
````

**Comment by Dgameman1** [comment]
Um, now when I Just go to the page, i get this error
http://i.imgur.com/HTMmo9n.png @cuonic

**Comment by cuonic** [comment]
Well that's good because now we know the problem. Either the file you are trying to send is not valid "media", try starting off by sending a small JPEG image, don't try videos / large images just yet. If not the the media type is invalid, try replacing `Snapchat::MEDIA_IMAGE` with `0` in upload.php

**Comment by Dgameman1** [comment]
@cuonic I didn't actually fill out the form anything. I just went to the page and it gave me that error =O

**Comment by cuonic** [comment]
Oh ok it's detecting a POST request by fetching the page... Oh dear. Replace Line 3 `if($_POST)` with `if(isset($_POST['username']))` and don't refresh the page after posting, just call it from the address bar.

**Comment by Dgameman1** [comment]
I changed the code and the same thing happens when i go to the page without posting lol
http://i.imgur.com/fG5VcD4.png
What if I make an ajax request and put the PHP into a different page?

**Comment by cuonic** [comment]
Damn, Ajax won't work for the file upload. How about changing line 3 to `if($_SERVER['REQUEST_METHOD'] == "POST")`

**Comment by Dgameman1** [comment]
@cuonic same error =/
Is it working with you?

**Comment by cuonic** [comment]
The original code works for me as well as all the modifications.

**Comment by cuonic** [comment]
What browser are you using ? What web server ?

**Comment by Dgameman1** [comment]
@cuonic I'm using google chrome and it's currently hosted up online

**Comment by cuonic** [comment]
Try running it locally with a WAMP / LAMP server

**Comment by Dgameman1** [comment]
Okay cool! So, this time nothing happened and the page loaded fine. I fill everything out and I get this
http://i.imgur.com/kleluAa.png
but I didn't log out of snapchat nor did it send anything

**Comment by cuonic** [comment]
This is not working very well at all for you. Are you sure you are using the provided snapchat.php and snapchat_agent.php ? Try using the following file as `snapchat.php` : https://gist.github.com/cuonic/bb106e1ce978ebf71c6e

**Comment by Dgameman1** [comment]
@cuonic This does not make any sense. I legit used the file you sent me to download but apparently the snapchat.php you just sent me to use on github is different. so I used that and now the error i get is this..

http://i.imgur.com/JfODLye.png

**Comment by cuonic** [comment]
Good, well something is screwing up with the login. Use the following as `snapchat_agent.php` : https://gist.github.com/cuonic/449a34af812fefc72522

**Comment by Dgameman1** [comment]
Still get the same No Authentication Details =/

Just want to say thank you so much btw

**Comment by Dgameman1** [comment]
But the thing is, it still logs me out :o

**Comment by cuonic** [comment]
Ok try adding the following  : 
````
echo "<pre>";
var_dump($login);
echo "</pre>";
````
just after `$login = $snapchat->login("username", "password");`

**Comment by Dgameman1** [comment]
http://i.imgur.com/FenPOEv.png

**Comment by cuonic** [comment]
There's the problem :) Try doing a Google search for that one

**Comment by Dgameman1** [comment]
@cuonic So I'm assuming the script doesn't see ca_bundle.crt
` curl_setopt($ch, CURLOPT_CAINFO, 'ca_bundle.crt');`

but ca_bundle.crt is with every other file?
![image](https://cloud.githubusercontent.com/assets/10294777/5602384/d7d2ab32-92fe-11e4-950e-76175e617b2d.png)

**Comment by cuonic** [comment]
@Dgameman1 : Curl requires an absolute path for the certificate file apparently, so you need to change line 318 of `snapchat_agent.php` with the full path : `curl_setopt($ch, CURLOPT_CAINFO, '/full/path/to/file/ca_bundle.crt');`

**Comment by cuonic** [comment]
Try the following line actually : `curl_setopt($ch, CURLOPT_CAINFO, dirname(__FILE__) . '/ca_bundle.crt');`

**Comment by Dgameman1** [comment]
@cuonic http://i.imgur.com/AtMMrBB.png

**Comment by cuonic** [comment]
@Dgameman1 Ok well that's a good start, login was successful via the new endpoint. You can remove the `var_dump($login);` stuff now. Is that the upload endpoint displaying the `UNSUPPORTED MEDIA TYPE` error ? Are you definitely uploading a JPEG image, relatively small ?

**Comment by KyleBoyer** [comment]
@cuonic Using this new endpoint, I've been able to send people images, just not post them to the story now... Is there a new endpoint for posting stories?

**Comment by cuonic** [comment]
@KyleBoyer : Watching the Android application's network traffic when posting a story it doesn't seem to use `/ph/upload` - it skips that step and does an "all-in-one" request with [/bq/retry_post_story](https://github.com/JorgenPhi/php-snapchat/wiki/API-v2-Research#bqretry_post_story)

**Comment by Dgameman1** [comment]
@cuonic You are god's gift to man kind. Thank you so much. But now how do you suggest we fix the post while refreshing when it's hosted up online?

**Comment by cuonic** [comment]
@Dgameman1 Glad you got everything working, happy to help :)

**Comment by KyleBoyer** [comment]
@cuonic @Dgameman1 How do you log in using an auth_token on the new API? I tried this:
```PHP
public function logina($username, $password) {
		$return['error'] = 1;

		$timestamp = parent::timestamp();
		$result = parent::post(
			'/loq/login',
			array(
				'username' => $username,
				'access_token' => $password,
				'timestamp' => $timestamp,
				'features_map' => array("all_updates_friends_response" => TRUE)
			),
			array(
				parent::STATIC_TOKEN,
				$timestamp,
			)
		);

		// Check if API request was successful

		if($result['error'] == 1) {
			return $result;
		}

		// Check if API response was successful

		
		if($result['data']->updates_response->logged == false) {
			$return['message'] = $result['data']->message;
			return $return;
		}

		// Logged in

		$this->auth_token = $result['data']->updates_response->auth_token;
		$this->username = $result['data']->updates_response->username;

		$return['error'] = 0;
		$return['message'] = "Logged in successfully.";
		$return['data'] = $result['data'];

		return $return;
	}
```
