### ISSUE TITLE
"The network you are connected to has been temporarily blocked because of suspicious activity"

### ISSUE THREAD

**Issue by Dgameman1** [JorgenPhi/php-snapchat#78]
So my code has been working great for a while now but then I was all of a sudden bombarded with this error message. 
Any idea on how to fix?
Is there a way to use proxies?

**Comment by Dgameman1** [comment]
Any ideas. I'm a bit confused because I still have the error even though it says temporarily

**Comment by NickAtSchool** [comment]
Perhaps try using a new account from a different IP address. It sounds like you may have been [ip] banned, just based on the error message - but I can't say for sure

**Comment by Dgameman1** [comment]
I used a proxy but now I get the error

array(3) {
  ["error"]=>
  int(1)
  ["message"]=>
  string(22) "API Connection failed."
  ["result"]=>
  string(73) "Failed connect to feelinsonice-hrd.appspot.com:3128; Connection timed out"
}

**Comment by cuonic** [comment]
@Dgameman1 It looks like you are trying to connect to the API URL via port 3128, which will not work.

**Comment by Dgameman1** [comment]
@cuonic
```
		CURLOPT_PROXY => '220.231.32.195',
		CURLOPT_PROXYPORT => '3128',
```
This is the code I added into it. I'm willing to pay you money to help fix me fix this at this point.

**Comment by JorgenPhi** [comment]
I wouldn't spend money on this, but I'm willing to help you out over Skype
in two hours if you would like.

**Comment by Dgameman1** [comment]
@JorgenPhi That sounds amazing. My skype name is Dgameman1

**Comment by JorgenPhi** [comment]
For those who want an interesting approach of bypassing this restriction, try proxying this library through a popular anonymizing network. Works like a charm.

**Comment by cuonic** [comment]
@JorgenPhi That's great as a short term solution but eventually all the exit nodes will get blocked by the API, or Snapchat will notice a load of Tor traffic coming to their API, which will result in them banning every connection from a Tor exit node.

**Comment by JorgenPhi** [comment]
Yes, it's a short term solution to a bigger problem, but how can we make it
not as "suspicious" ? Who says the official app doesn't make some call over
a proprietary protocol (the chat protocol for instance) or something
similar that we aren't mimicking?

**Comment by cuonic** [comment]
I have a web app in development using a modified version of the class sending out randomized User Agents (8.1.1 / 8.1.1 Beta / 8.1.2 - Nexus 4 / Nexus 7 / HTC One / Motorola X) and after login I make a request to `/ph/device` sending a random device token. Then just make sure you don't log in for every request to the API by keeping the `auth_token` and `username` as cookies in the user's browser, or in a database.

I haven't had time to look at the chat protocol, does it make a direct TCP connection to the "gateway server" or something ? Snapchat could do something clever like that to keep us out, but for the moment they haven't been very innovative like that.

**Comment by chandu4ugandhi** [comment]
@JorgenPhi I have sent you the request over the skype for resolve this same bug. I am facing "The network you are connected to has been temporarily blocked because of suspicious activity" bug.
