### ISSUE TITLE
API returning error

### ISSUE THREAD

**Issue by ahmed-usman** [JorgenPhi/php-snapchat#79]
My account is not locked and my password and everything is correct. It's still returning this error:

PHP Notice:  Undefined property: Snapchat::$cache in /home/username/Desktop/NHSO/src/snapchat.php on line 234

PHP Fatal error:  Call to a member function get() on a non-object in /home/username/Desktop/NHSO/src/snapchat.php on line 234

**Comment by hisham-albeik** [comment]
The account might not be locked but the IP address you're connecting from might be blocked. Sometimes you an get blocked and not get the "ip address you connected from" error message. Also, if you haven't used it in a while you might be missing the header update that is either waiting for a pull request or recently merged. I think if you look at the github project and look in the pull requests you'll see the latest chnages. Again I'm not sure if it is merged yet, so you might need to look into closed requests if it was.

Also, it's no coincidence that you are getting it at the same time as another person who received the blocked IP address error message. I believe they do it in batches during certain intervals.

First try changing IP address, if you can't then maybe try connecting through a VPN, Tor, or a proxy. (Unsure how you would do it through a proxy)

**Comment by Dgameman1** [comment]
I'm also getting an error made an issue #78 
I'll try and figure something out and get back to you on it.

**Comment by LinoSuarez** [comment]
Just use this <a href="https://github.com/JorgenPhi/php-snapchat/pull/80">#80</a>

**Comment by hako** [comment]
@Dgameman1 please try @LinoSuarez's fix and could you tell us if it works for you or not?

**Comment by imlordeyaya** [comment]
did it and it still does not work.

**Comment by ThePengwin** [comment]
@LinoSuarez : thanks, that has fixed things up for me for now.

Just a note though: I set up and watched the latest snapchat on android and instead of posting to /bq/login/ it is now posting to /loq/login. Im guessing in the future this may cause issues with logging in.

**Comment by Dgameman1** [comment]
@hako @LinoSuarez Tried it and it still didn't work.
Is there any way to use a proxy with this?

**Comment by hako** [comment]
@Dgameman1 what's your current setup? How are you running the php-snapchat library?

**Comment by Dgameman1** [comment]
@hako On my website. I believe the website's IP is banned now =/

**Comment by LinoSuarez** [comment]
It's possible to use proxy -> stream_context_set_default(['http'=>['proxy'=>'proxy-host:proxy-port']]);

**Comment by ahmed-usman** [comment]
I found a fix. I used a different Device thing. I'm not sure I got it from somewhere else. My account wasn't blocked, Snapchat just wasn't letting me log in the same way I used to.

**Comment by Dgameman1** [comment]
@LinoSuarez Do you know where I would add this information?
