### ISSUE TITLE
.key file to go along with the crt?

### ISSUE THREAD

**Issue by Snowlav** [JorgenPhi/php-snapchat#84]
My android will only install .p12 files.
Since I only have a ca_bundle.crt I need a .key file to convert it into a .p12 

Thanks in advance.

**Comment by Dubz** [comment]
You do know that this isn't meant to be installed on your phone or anything right? The src files dont need to be modified/installed, you just need PHP installed on a computer and knowledge of coding to make it work. This isn't a program to do it for you, its a resource that has part of that program done for you.

**Comment by JorgenPhi** [comment]
The CA_bundle is a package for the library to verify that a ssl cert is
valid. It shouldn't need to be installed on your phone. If you want to do
research, you use a proxy and install that ssl cert on your phone. See
Charles Proxy or Fiddler for more info on that.

Also, nice dubs.

**Comment by Snowlav** [comment]
yeah I done goofed, currently documenting the 42 endpoints I have found :)
