### ISSUE TITLE
I think I know how to send text messages, is there anyone that can test with me?

### ISSUE THREAD

**Issue by Snowlav** [JorgenPhi/php-snapchat#85]
I have the endpoints needed, sequence, requests and responses.
If anyone wants to test this with me, let me know :)

**Comment by hako** [comment]
@Snowlav I'll be happy to test this.

**Comment by Snowlav** [comment]
ok I have you email, I will send the info to you right now :)

**Comment by Snowlav** [comment]
Email is send to you @hako please let me know when you receive it.
I forgot to save some info on the auth_token which I am getting back now and sending to you.

**Comment by Maraumax** [comment]
I would also be interested to try!

**Comment by Snowlav** [comment]
@Maraumax thanks for your interest, there is further testing needed on tcp level.
Will update once I find out more :)

**Comment by KyleBoyer** [comment]
@Snowlav Can you get ahold of me at Xtremeness [@t] live.com for snapchat text messages?
