### ISSUE TITLE
Register question

### ISSUE THREAD

**Issue by mgp25** [JorgenPhi/php-snapchat#86]
Hi there, im trying out this API, and im currently using @hako one.

I have done these steps already:

- git clone https://github.com/hako/php-snapchat and switch to the snaptcha branch
   - git checkout snaptcha
- apply the header fix to `snapchat_agent.php` or download the patch here
- download the example
- change the `$email` and `$username` to whatever you want to register.
- run `php [example file].php`

I got this output (normal):

```
mgp25$ php /Users/mgp25/Desktop/php-snapchat-snaptcha/snap.php

Warning: First parameter must either be an object or the name of an existing class in /Users/mgp25/Desktop/php-snapchat-snaptcha/src/snapchat.php on line 239

captcha: 
```

But no .zip file was downloaded, and my question is, is this still working or is there any other workaround? Maybe im doing something wrong.

Related issue: #73 

Regards

**Comment by hako** [comment]
I'm going to test this and get back to you, it should be working but this might need an a rewrite since it uses both old and new endpoints in order to enable register functionality.

**Comment by mgp25** [comment]
@hako thanks! i'll start reverse engineering SnapChat this week, hope i can help improving this API. Let me know if i was doing something wrong.

Regards
